# syntax=docker/dockerfile:1
FROM python:3.10-alpine
WORKDIR '/code'
# set environments
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
# install packages
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
# set listen port
EXPOSE 5000
COPY . .
# default command "flask run"
CMD ["flask", "run"]